// SelectorsHub MCP server: gives AI agents SelectorsHub's locator engine.
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseConfig, HELP } from "./config.js";
import { Session, UserError } from "./session.js";
import { FRAMEWORKS } from "./codegen.js";
import {
  listElements,
  formatList,
  generateLocators,
  validateLocator,
  fixLocator,
  generatePageObject,
  pageAction,
  screenshot,
} from "./locators.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
let engineVersion = "";
try {
  const v = JSON.parse(readFileSync(join(ROOT, "engine", "vendor", "VERSION.json"), "utf8"));
  engineVersion = `${v.extension} ${v.extensionVersion}`;
} catch {}

const INSTRUCTIONS = `SelectorsHub gives you verified, reliable element locators (XPath, CSS, Playwright, Selenium, Cypress, WebdriverIO) generated by the SelectorsHub engine against the real page, including shadow DOM, iframes and SVG.

Use it instead of guessing locators whenever you write or repair UI automation:
1. open_page to load the app (the browser keeps logins between sessions; use page_action to click through to the state you need).
2. list_elements to see interactive elements with refs and their best locators.
3. generate_locators for the full set for one element (by ref, locator or visible text), with ready-to-paste code for the user's framework.
4. validate_locator to check any locator's match count; fix_locator to repair broken or ambiguous ones; generate_page_object for a whole page.
Always prefer the "recommended" locators, and pass the user's framework in "frameworks" so the code matches their stack.`;

const targetShape = {
  ref: z.string().optional().describe('Element ref from list_elements or an earlier result, e.g. "e12"'),
  locator: z.string().optional().describe("Any existing locator: XPath, CSS, Playwright (JS/Python/Java/C#), Selenium By.*, Cypress cy.get()"),
  text: z.string().optional().describe("Visible text, label, placeholder, aria-label or title of the element"),
  nth: z.number().int().positive().optional().describe("1-based index when the locator matches several elements"),
};
const frameworksShape = z
  .array(z.enum(FRAMEWORKS))
  .optional()
  .describe("Frameworks to generate ready-to-paste code for, e.g. ['playwright-ts'] or ['selenium-java']");

export async function createServer(config) {
  const session = new Session(config);
  const server = new McpServer({ name: "selectorshub", version: pkg.version }, { instructions: INSTRUCTIONS });

  const text = (s) => ({ content: [{ type: "text", text: typeof s === "string" ? s : JSON.stringify(s, null, 2) }] });
  const fail = (s) => ({ content: [{ type: "text", text: s }], isError: true });

  // All tools are free and unlimited: no license key, no usage counting.
  const tool = (name, def, handler) =>
    server.registerTool(name, def, async (args) => {
      try {
        return await handler(args || {});
      } catch (e) {
        if (e instanceof UserError) return fail(e.message);
        const msg = String((e && e.message) || e);
        if (/Target page, context or browser has been closed|Browser has been closed/i.test(msg)) {
          await session.close();
          return fail("The browser was closed. Call open_page to start again.");
        }
        return fail(`SelectorsHub error: ${msg.split("\n").slice(0, 6).join("\n")}`);
      }
    });

  const target = (a) => ({ ref: a.ref, locator: a.locator, text: a.text, nth: a.nth });

  tool(
    "open_page",
    {
      title: "Open page",
      description: "Open a URL in the SelectorsHub browser (keeps cookies/logins between sessions). Call this before other tools.",
      inputSchema: {
        url: z.string().describe("URL to open"),
        wait_until: z.enum(["load", "domcontentloaded", "networkidle", "commit"]).optional().describe("Default: load"),
      },
      annotations: { readOnlyHint: false, openWorldHint: true },
    },
    async ({ url, wait_until }) => {
      const resp = await session.navigate(url, wait_until || "load");
      const page = await session.getPage();
      const frames = await session.frames();
      return text({
        url: page.url(),
        title: await page.title().catch(() => ""),
        status: resp ? resp.status() : undefined,
        iframes: frames.length - 1,
        next: "Call list_elements to see the elements and their locators.",
      });
    }
  );

  tool(
    "list_elements",
    {
      title: "List elements",
      description:
        "List interactive elements on the current page (including inside open shadow DOM and iframes) with refs and their best Playwright and Selenium locators.",
      inputSchema: {
        filter: z.string().optional().describe('Only elements whose text/attributes contain this, e.g. "login" or "button"'),
        include_hidden: z.boolean().optional().describe("Include invisible elements (default false)"),
        include_text: z.boolean().optional().describe("Also include non-interactive text elements such as headings and cells"),
        limit: z.number().int().positive().max(500).optional().describe("Max elements (default 150)"),
      },
      annotations: { readOnlyHint: true },
    },
    async (a) => {
      const res = await listElements(session, { filter: a.filter, includeHidden: a.include_hidden, includeText: a.include_text, limit: a.limit });
      return text(formatList(res));
    }
  );

  tool(
    "generate_locators",
    {
      title: "Generate locators",
      description:
        "Generate all SelectorsHub locators for one element: relative/indexed/absolute XPath, CSS, id/name/class/linkText, Playwright locators, testRigor path, shadow DOM host chain and iframe chain, each with its match count, plus a recommended pick and optional ready-to-paste code. Identify the element by ref, an existing locator, or its visible text/label.",
      inputSchema: {
        ...targetShape,
        frameworks: frameworksShape,
        preferred_attribute: z.string().optional().describe('Custom attribute to prefer, e.g. "data-qa" or "data-test-id"'),
        exclude: z
          .array(z.enum(["id", "class", "name", "placeholder", "text"]))
          .optional()
          .describe("Attributes the locators must not rely on (e.g. ['id'] when ids are generated)"),
        relative_to: z
          .object(targetShape)
          .optional()
          .describe("A stable anchor element; adds a SelectorsHub axes XPath locating the target relative to it"),
      },
      annotations: { readOnlyHint: true },
    },
    async (a) => {
      const out = await generateLocators(session, target(a), {
        frameworks: a.frameworks,
        preferredAttribute: a.preferred_attribute,
        exclude: a.exclude,
        anchor: a.relative_to ? target(a.relative_to) : null,
      });
      return text(out);
    }
  );

  tool(
    "validate_locator",
    {
      title: "Validate locator",
      description:
        "Check a locator against the current page: syntax errors (with auto-correction), match count across frames and shadow DOM, uniqueness, fragility warnings, and a unique alternative when it matches several elements. Accepts XPath, CSS, Playwright (JS/Python/Java/C#), Selenium By.*, Cypress and WebdriverIO forms.",
      inputSchema: { locator: z.string().describe("The locator to check") },
      annotations: { readOnlyHint: true },
    },
    async ({ locator }) => text(await validateLocator(session, locator))
  );

  tool(
    "fix_locator",
    {
      title: "Fix locator",
      description:
        "Repair a broken locator: corrects syntax errors, disambiguates locators that match several elements, and when a locator matches nothing (e.g. after a UI change) finds the element it was targeting and returns a new reliable locator.",
      inputSchema: {
        locator: z.string().describe("The broken or suspect locator"),
        hint: z.string().optional().describe('What the element is, e.g. "the login submit button"; improves matching after UI changes'),
        frameworks: frameworksShape,
      },
      annotations: { readOnlyHint: true },
    },
    async (a) => text(await fixLocator(session, a.locator, { hint: a.hint, frameworks: a.frameworks }))
  );

  tool(
    "generate_page_object",
    {
      title: "Generate page object",
      description:
        "Generate a page object class for the current page (or chosen elements) with the best locator for every element, in the requested framework and language. Handles iframes and shadow DOM.",
      inputSchema: {
        framework: z.enum(FRAMEWORKS).describe("Target framework and language"),
        class_name: z.string().optional().describe("Class name (default derived from the page title)"),
        refs: z.array(z.string()).optional().describe("Only these element refs (default: all visible interactive elements)"),
        filter: z.string().optional().describe("Only elements whose text/attributes contain this"),
        preferred_attribute: z.string().optional().describe('Custom attribute to prefer, e.g. "data-qa"'),
        limit: z.number().int().positive().max(200).optional().describe("Max elements (default 60)"),
      },
      annotations: { readOnlyHint: true },
    },
    async (a) => {
      const res = await generatePageObject(session, {
        framework: a.framework,
        className: a.class_name,
        refs: a.refs,
        filter: a.filter,
        preferredAttribute: a.preferred_attribute,
        limit: a.limit,
      });
      return text(`${res.className} (${a.framework}, ${res.count} elements)\n\n${res.code}`);
    }
  );

  tool(
    "page_action",
    {
      title: "Page action",
      description:
        "Interact with the page to reach the state you need locators for (log in, open a menu, go to the next step). Identify the element by ref, locator or text.",
      inputSchema: {
        action: z.enum(["click", "dblclick", "hover", "fill", "type", "press", "check", "uncheck", "select", "focus", "wait", "back", "reload"]),
        ...targetShape,
        value: z.string().optional().describe("Text for fill/type, key for press (e.g. Enter), option for select, milliseconds for wait"),
      },
      annotations: { readOnlyHint: false, destructiveHint: false },
    },
    async (a) => {
      const hasTarget = a.ref || a.locator || a.text;
      const res = await pageAction(session, hasTarget ? target(a) : null, a.action, a.value);
      return text({ done: a.action, ...res, next: "Refs from before a navigation are stale; call list_elements again if the page changed." });
    }
  );

  tool(
    "screenshot",
    {
      title: "Screenshot",
      description: "Screenshot the page, or one element highlighted in SelectorsHub orange (to confirm a locator points at the right thing).",
      inputSchema: targetShape,
      annotations: { readOnlyHint: true },
    },
    async (a) => {
      const hasTarget = a.ref || a.locator || a.text;
      const buf = await screenshot(session, hasTarget ? target(a) : null);
      return { content: [{ type: "image", data: buf.toString("base64"), mimeType: "image/png" }] };
    }
  );

  tool(
    "close_browser",
    {
      title: "Close browser",
      description: "Close the SelectorsHub browser. It reopens automatically on the next open_page.",
      inputSchema: {},
      annotations: { readOnlyHint: false },
    },
    async () => {
      await session.close();
      return text("Browser closed.");
    }
  );

  return { server, session };
}

export async function main() {
  const config = parseConfig();
  if (config.help) {
    process.stdout.write(HELP);
    return;
  }
  if (config.version) {
    process.stdout.write(pkg.version + "\n");
    return;
  }
  const { server, session } = await createServer(config);
  const shutdown = async () => {
    await session.close();
    process.exit(0);
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);
  process.stdin.on("close", shutdown);
  await server.connect(new StdioServerTransport());
  process.stderr.write(`SelectorsHub MCP ${pkg.version} ready${engineVersion ? ` (engine: ${engineVersion})` : ""}\n`);
}
